server:
  port: 9191
  
spring:
  application:
    name: API-GATEWAY
  devtools:
      restart:
         enabled: true
  cloud:
     gateway:
        # discovery locator is the auto-alternative to manually configuring the API-Routes
        # Also works with manual routes enabled as well for both (/USER-SERVICE/users/ & /users/)
#          discovery:
#             locator:
#                enabled: false
#                lower-case-service-id: true
          routes:
           - id: USER-SERVICE-status-check
             uri: lb://USER-SERVICE
             predicates:
               # Controller level GetMapping Path
               - Path=/api/users/status/check
#               - Path=/api/users/**
#               - Path=/USER-SERVICE/api/users/status/check
               - Header=Authorization, Bearer (.*)
             filters:
               # Runs AuthorizationHeaderFilter method in Main Package
               - AuthorizationHeaderFilter
               # URL segment in PrefixPath must not be included in URL (localhost:9191/users NOT localhost:9191/api/users)
#               - PrefixPath=/api
               - RemoveRequestHeader=Cookie
#               - RewritePath=/USER-SERVICE/api/users/status/check, /api/users/status/check
#               - RewritePath=/USER-SERVICE/(?<segment>.*), /$\{<segment>}


           - id: USER-SERVICE-create
             uri: lb://USER-SERVICE
             predicates:
               # Controller level PostMapping Path
               - Path=/api/users/create
             filters:
               - RemoveRequestHeader=Cookie


           - id: USER-SERVICE-login
             uri: lb://USER-SERVICE
             predicates:
               # Controller level PostMapping Path
               - Path=/api/users/login
             filters:
               - RemoveRequestHeader=Cookie
  
               
           - id: USER-SERVICE-update
             uri: lb://USER-SERVICE
             predicates:
               # Controller level PostMapping Path
               - Path=/api/users/update
               - Header=Authorization, Bearer (.*)
             filters:
               # Runs AuthorizationHeaderFilter method in Main Package
               - AuthorizationHeaderFilter
               - RemoveRequestHeader=Cookie
               
               
           - id: USER-SERVICE-delete
             uri: lb://USER-SERVICE
             predicates:
               # Controller level PostMapping Path
               - Path=/api/users/delete
               - Header=Authorization, Bearer (.*)
             filters:
               # Runs AuthorizationHeaderFilter method in Main Package
               - AuthorizationHeaderFilter
               - RemoveRequestHeader=Cookie




                 
           - id: ACCOUNT-MANAGEMENT-SERVICE
             uri: lb://ACCOUNT-MANAGEMENT-SERVICE
             predicates:
               # Controller level GetMapping Path
               - Path=/api/accounts/**
             filters:
               # URL segment in PrefixPath must not be included in URL (localhost:9191/users NOT localhost:9191/api/users)
#               - PrefixPath=/api
               - RemoveRequestHeader=Cookie
               - AuthorizationHeaderFilter
#
#  main:
#     web:
#        web-application-type: reactive
    


    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
    
token:
   # 10 days
   expiration_time: 864000000
   secret: heyN0w61